apiVersion: v1
kind: Service
metadata:
  name: "postgres"
  namespace: dev
  labels:
    name: "postgres"
spec:
  ports:
  - name: "postgres"
    protocol: "TCP"
    port: 5432
    targetPort: 5432
  selector:
    name: postgres

